{{- if .Values.apiServer.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "bc-wallet.fullname" . }}-{{ .Values.apiServer.serviceAccount.name }}
  namespace: {{ .Values.global.namespaceOverride | default .Release.Namespace }}
  labels:
    {{- include "bc-wallet.labels" . | nindent 4 }}
{{- end }}
---
{{- if .Values.demoServer.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "bc-wallet.fullname" . }}-{{ .Values.demoServer.serviceAccount.name }}
  namespace: {{ .Values.global.namespaceOverride | default .Release.Namespace }}
  labels:
    {{- include "bc-wallet.labels" . | nindent 4 }}
{{- end }}
---
{{- if .Values.demoWeb.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "bc-wallet.fullname" . }}-{{ .Values.demoWeb.serviceAccount.name }}
  namespace: {{ .Values.global.namespaceOverride | default .Release.Namespace }}
  labels:
    {{- include "bc-wallet.labels" . | nindent 4 }}
{{- end }}
---
{{- if .Values.showcaseCreator.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "bc-wallet.fullname" . }}-{{ .Values.showcaseCreator.serviceAccount.name }}
  namespace: {{ .Values.global.namespaceOverride | default .Release.Namespace }}
  labels:
    {{- include "bc-wallet.labels" . | nindent 4 }}
{{- end }}
---
{{- if .Values.tractionAdapter.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "bc-wallet.fullname" . }}-{{ .Values.tractionAdapter.serviceAccount.name }}
  namespace: {{ .Values.global.namespaceOverride | default .Release.Namespace }}
  labels:
    {{- include "bc-wallet.labels" . | nindent 4 }}
{{- end }} 