"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Credential Showcase API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.IssuanceScenarioTypeEnum = void 0;
exports.instanceOfIssuanceScenario = instanceOfIssuanceScenario;
exports.IssuanceScenarioFromJSON = IssuanceScenarioFromJSON;
exports.IssuanceScenarioFromJSONTyped = IssuanceScenarioFromJSONTyped;
exports.IssuanceScenarioToJSON = IssuanceScenarioToJSON;
exports.IssuanceScenarioToJSONTyped = IssuanceScenarioToJSONTyped;
const Persona_1 = require("./Persona");
const Issuer_1 = require("./Issuer");
const Step_1 = require("./Step");
/**
 * @export
 */
exports.IssuanceScenarioTypeEnum = {
    Issuance: 'ISSUANCE'
};
/**
 * Check if a given object implements the IssuanceScenario interface.
 */
function instanceOfIssuanceScenario(value) {
    if (!('id' in value) || value['id'] === undefined)
        return false;
    if (!('name' in value) || value['name'] === undefined)
        return false;
    if (!('slug' in value) || value['slug'] === undefined)
        return false;
    if (!('description' in value) || value['description'] === undefined)
        return false;
    if (!('type' in value) || value['type'] === undefined)
        return false;
    if (!('steps' in value) || value['steps'] === undefined)
        return false;
    if (!('personas' in value) || value['personas'] === undefined)
        return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined)
        return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined)
        return false;
    if (!('issuer' in value) || value['issuer'] === undefined)
        return false;
    return true;
}
function IssuanceScenarioFromJSON(json) {
    return IssuanceScenarioFromJSONTyped(json, false);
}
function IssuanceScenarioFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'id': json['id'],
        'name': json['name'],
        'slug': json['slug'],
        'description': json['description'],
        'type': json['type'],
        'steps': (json['steps'].map(Step_1.StepFromJSON)),
        'personas': (json['personas'].map(Persona_1.PersonaFromJSON)),
        'hidden': json['hidden'] == null ? undefined : json['hidden'],
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
        'issuer': (0, Issuer_1.IssuerFromJSON)(json['issuer']),
    };
}
function IssuanceScenarioToJSON(json) {
    return IssuanceScenarioToJSONTyped(json, false);
}
function IssuanceScenarioToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    return {
        'id': value['id'],
        'name': value['name'],
        'slug': value['slug'],
        'description': value['description'],
        'type': value['type'],
        'steps': (value['steps'].map(Step_1.StepToJSON)),
        'personas': (value['personas'].map(Persona_1.PersonaToJSON)),
        'hidden': value['hidden'],
        'createdAt': ((value['createdAt']).toISOString()),
        'updatedAt': ((value['updatedAt']).toISOString()),
        'issuer': (0, Issuer_1.IssuerToJSON)(value['issuer']),
    };
}
//# sourceMappingURL=IssuanceScenario.js.map