"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Credential Showcase API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.PresentationScenarioTypeEnum = void 0;
exports.instanceOfPresentationScenario = instanceOfPresentationScenario;
exports.PresentationScenarioFromJSON = PresentationScenarioFromJSON;
exports.PresentationScenarioFromJSONTyped = PresentationScenarioFromJSONTyped;
exports.PresentationScenarioToJSON = PresentationScenarioToJSON;
exports.PresentationScenarioToJSONTyped = PresentationScenarioToJSONTyped;
const RelyingParty_1 = require("./RelyingParty");
const Persona_1 = require("./Persona");
const Step_1 = require("./Step");
/**
 * @export
 */
exports.PresentationScenarioTypeEnum = {
    Presentation: 'PRESENTATION'
};
/**
 * Check if a given object implements the PresentationScenario interface.
 */
function instanceOfPresentationScenario(value) {
    if (!('id' in value) || value['id'] === undefined)
        return false;
    if (!('name' in value) || value['name'] === undefined)
        return false;
    if (!('slug' in value) || value['slug'] === undefined)
        return false;
    if (!('description' in value) || value['description'] === undefined)
        return false;
    if (!('type' in value) || value['type'] === undefined)
        return false;
    if (!('steps' in value) || value['steps'] === undefined)
        return false;
    if (!('personas' in value) || value['personas'] === undefined)
        return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined)
        return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined)
        return false;
    if (!('relyingParty' in value) || value['relyingParty'] === undefined)
        return false;
    return true;
}
function PresentationScenarioFromJSON(json) {
    return PresentationScenarioFromJSONTyped(json, false);
}
function PresentationScenarioFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'id': json['id'],
        'name': json['name'],
        'slug': json['slug'],
        'description': json['description'],
        'type': json['type'],
        'steps': (json['steps'].map(Step_1.StepFromJSON)),
        'personas': (json['personas'].map(Persona_1.PersonaFromJSON)),
        'hidden': json['hidden'] == null ? undefined : json['hidden'],
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
        'relyingParty': (0, RelyingParty_1.RelyingPartyFromJSON)(json['relyingParty']),
    };
}
function PresentationScenarioToJSON(json) {
    return PresentationScenarioToJSONTyped(json, false);
}
function PresentationScenarioToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    return {
        'id': value['id'],
        'name': value['name'],
        'slug': value['slug'],
        'description': value['description'],
        'type': value['type'],
        'steps': (value['steps'].map(Step_1.StepToJSON)),
        'personas': (value['personas'].map(Persona_1.PersonaToJSON)),
        'hidden': value['hidden'],
        'createdAt': ((value['createdAt']).toISOString()),
        'updatedAt': ((value['updatedAt']).toISOString()),
        'relyingParty': (0, RelyingParty_1.RelyingPartyToJSON)(value['relyingParty']),
    };
}
//# sourceMappingURL=PresentationScenario.js.map
