"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Credential Showcase API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ShowcaseScenariosInnerFromJSON = ShowcaseScenariosInnerFromJSON;
exports.ShowcaseScenariosInnerFromJSONTyped = ShowcaseScenariosInnerFromJSONTyped;
exports.ShowcaseScenariosInnerToJSON = ShowcaseScenariosInnerToJSON;
exports.ShowcaseScenariosInnerToJSONTyped = ShowcaseScenariosInnerToJSONTyped;
const IssuanceScenario_1 = require("./IssuanceScenario");
const PresentationScenario_1 = require("./PresentationScenario");
function ShowcaseScenariosInnerFromJSON(json) {
    return ShowcaseScenariosInnerFromJSONTyped(json, false);
}
function ShowcaseScenariosInnerFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    switch (json['type']) {
        case 'ISSUANCE':
            return Object.assign({}, (0, IssuanceScenario_1.IssuanceScenarioFromJSONTyped)(json, true), { type: 'ISSUANCE' });
        case 'PRESENTATION':
            return Object.assign({}, (0, PresentationScenario_1.PresentationScenarioFromJSONTyped)(json, true), { type: 'PRESENTATION' });
        default:
            throw new Error(`No variant of ShowcaseScenariosInner exists with 'type=${json['type']}'`);
    }
}
function ShowcaseScenariosInnerToJSON(json) {
    return ShowcaseScenariosInnerToJSONTyped(json, false);
}
function ShowcaseScenariosInnerToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    switch (value['type']) {
        case 'ISSUANCE':
            return Object.assign({}, (0, IssuanceScenario_1.IssuanceScenarioToJSON)(value), { type: 'ISSUANCE' });
        case 'PRESENTATION':
            return Object.assign({}, (0, PresentationScenario_1.PresentationScenarioToJSON)(value), { type: 'PRESENTATION' });
        default:
            throw new Error(`No variant of ShowcaseScenariosInner exists with 'type=${value['type']}'`);
    }
}
//# sourceMappingURL=ShowcaseScenariosInner.js.map