{{- if .Values.demoWeb.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bc-wallet.fullname" . }}-demo-web
  namespace: {{ .Values.global.namespaceOverride | default .Release.Namespace }}
  labels:
    app.kubernetes.io/component: demo-web
    app.kubernetes.io/part-of: bc-wallet
    {{- include "bc-wallet.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.demoWeb.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/component: demo-web
      {{- include "bc-wallet.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.demoWeb.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app.kubernetes.io/component: demo-web
        {{- include "bc-wallet.labels" . | nindent 8 }}
        {{- with .Values.demoWeb.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.demoWeb.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ if .Values.demoWeb.serviceAccount.create }}{{ include "bc-wallet.fullname" . }}-{{ .Values.demoWeb.serviceAccount.name }}{{ end }}
      {{- with .Values.demoWeb.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: demo-web
          {{- with .Values.demoWeb.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.demoWeb.image.repository }}:{{ .Values.demoWeb.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.demoWeb.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.demoWeb.port }}
              protocol: TCP
          env:
            - name: NEXT_PUBLIC_API_URL
              value: {{ .Values.demoWeb.env.NEXT_PUBLIC_API_URL | quote }}
            - name: NEXT_PUBLIC_SHOWCASE_API_URL
              value: {{ .Values.demoWeb.env.NEXT_PUBLIC_SHOWCASE_API_URL | quote }}
            - name: NEXT_AUTH_SECRET
              value: {{ .Values.demoWeb.env.NEXT_AUTH_SECRET | quote }}
            - name: OIDC_DEFAULT_TENANT
              value: {{ .Values.demoWeb.env.OIDC_DEFAULT_TENANT | quote }}
            - name: OIDC_TRUST_HOST
              value: {{ .Values.demoWeb.env.OIDC_TRUST_HOST | quote }}
            - name: OIDC_AUTH_URL
              value: {{ .Values.demoWeb.env.OIDC_AUTH_URL | quote }}
          {{- include "bc-wallet.renderEnvFrom" (list "demoWeb" .) | nindent 10 }}
          {{- with .Values.demoWeb.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.demoWeb.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.demoWeb.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.demoWeb.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.demoWeb.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.demoWeb.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.demoWeb.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.demoWeb.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }} 