nameOverride: ""
fullnameOverride: "bc-wallet"

global:
  namespaceOverride: ""
  # Optional: name of ConfigMap with extra environment variables to be used by all components
  extraEnvVarsCM: ""
  # Optional: name of Secret with extra environment variables to be used by all components
  extraEnvVarsSecret: ""

# This block is for setting up the ingress for more information can be found here: https://kubernetes.io/docs/concepts/services-networking/ingress/
ingress:
  enabled: true
  className: "traefik"
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
  hosts:
    - host: api.bc-wallet-demo.dev.nborbit.ca
      paths:
        - path: /
          service: bc-wallet-demo-api-server
          port: 3000
    - host: traction.bc-wallet-demo.dev.nborbit.ca
      paths:  
        - path: /
          service: bc-wallet-demo-traction-adapter
          port: 3000
    - host: showcase.bc-wallet-demo.dev.nborbit.ca
      paths:
        - path: /
          service: bc-wallet-demo-showcase-creator
          port: 3050
    - host: demo-web.bc-wallet-demo.dev.nborbit.ca
      paths:
        - path: /
          service: bc-wallet-demo-demo-web
          port: 80
    - host: demo-server.bc-wallet-demo.dev.nborbit.ca
      paths:
        - path: /
          service: bc-wallet-demo-demo-server
          port: 3000
  tls:
    - secretName: bc-wallet-tls
      hosts:
        - api.bc-wallet-demo.dev.nborbit.ca
        - traction.bc-wallet-demo.dev.nborbit.ca
        - showcase.bc-wallet-demo.dev.nborbit.ca
        - demo-web.bc-wallet-demo.dev.nborbit.ca
        - demo-server.bc-wallet-demo.dev.nborbit.ca

# This section builds out the service account more information can be found here: https://kubernetes.io/docs/concepts/security/service-accounts/
serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Automatically mount a ServiceAccount's API credentials?
  automount: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

apiServer:
  # This will set the replicaset count more information can be found here: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/
  replicaCount: 1

  # This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
  image:
    repository: ghcr.io/4sure-tech/bc-wallet-api-server
    # This sets the pull policy for images.
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""

  # This is for the secrets for pulling an image from a private repository more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
  imagePullSecrets: []

  # Name of ConfigMap with extra environment variables; overrides global.extraEnvVarsCM if set
  extraEnvVarsCM: ""

  # Name of Secret with extra environment variables; overrides global.extraEnvVarsSecret if set
  extraEnvVarsSecret: ""

  # This is for setting Kubernetes Annotations to a Pod.
  podAnnotations: {}
  # This is for setting Kubernetes Labels to a Pod.
  podLabels: {}

  podSecurityContext: {}

  securityContext: {}

  # This is for setting up a service more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/
  service:
    type: ClusterIP
    port: 3000

  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

  # This is to setup the liveness and readiness probes more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
  livenessProbe: {}
  readinessProbe: {}

  # This section is for setting up autoscaling more information can be found here: https://kubernetes.io/docs/concepts/workloads/autoscaling/
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80
    stabilizationWindowSeconds: 300

  networkPolicy:
    enabled: false
    ingress:
      enabled: false
      namespaceSelector: {}
      podSelector: {}

  # Additional volumes on the output Deployment definition.
  volumes: []

  # Additional volumeMounts on the output Deployment definition.
  volumeMounts: []

  nodeSelector: {}

  tolerations: []

  affinity: {}

demoServer:
  # This will set the replicaset count more information can be found here: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/
  replicaCount: 1

  # This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
  image:
    repository: ghcr.io/4sure-tech/bc-wallet-demo-server
    # This sets the pull policy for images.
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""

  # This is for the secrets for pulling an image from a private repository more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
  imagePullSecrets: []

  logLevel: debug

  # Name of ConfigMap with extra environment variables; overrides global.extraEnvVarsCM if set
  extraEnvVarsCM: ""

  # Name of Secret with extra environment variables; overrides global.extraEnvVarsSecret if set
  extraEnvVarsSecret: ""

  # This is for setting Kubernetes Annotations to a Pod.
  podAnnotations: {}
  # This is for setting Kubernetes Labels to a Pod.
  podLabels: {}

  podSecurityContext: {}

  securityContext: {}

  # This is for setting up a service more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/
  service:
    type: ClusterIP
    port: 3000

  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

  # This is to setup the liveness and readiness probes more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
  livenessProbe: {}
  readinessProbe: {}

  # This section is for setting up autoscaling more information can be found here: https://kubernetes.io/docs/concepts/workloads/autoscaling/
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80
    stabilizationWindowSeconds: 300

  networkPolicy:
    enabled: false
    ingress:
      enabled: false
      namespaceSelector: {}
      podSelector: {}

  # Additional volumes on the output Deployment definition.
  volumes: []

  # Additional volumeMounts on the output Deployment definition.
  volumeMounts: []

  nodeSelector: {}

  tolerations: []

  affinity: {}

demoWeb:
  # This will set the replicaset count more information can be found here: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/
  replicaCount: 1

  # This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
  image:
    repository: ghcr.io/4sure-tech/bc-wallet-demo-web
    # This sets the pull policy for images.
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""

  # This is for the secrets for pulling an image from a private repository more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
  imagePullSecrets: []

  logLevel: debug
  baseRoute: /digital-trust/showcase
  snowplowEndpoint: spm.apps.gov.bc.ca
  insightsProjectId: your_insights_project_id

  # Name of ConfigMap with extra environment variables; overrides global.extraEnvVarsCM if set
  extraEnvVarsCM: ""

  # Name of Secret with extra environment variables; overrides global.extraEnvVarsSecret if set
  extraEnvVarsSecret: ""

  # This is for setting Kubernetes Annotations to a Pod.
  podAnnotations: {}
  # This is for setting Kubernetes Labels to a Pod.
  podLabels: {}

  podSecurityContext: {}

  securityContext: {}

  # This is for setting up a service more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/
  service:
    type: ClusterIP
    port: 3000

  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

  # This is to setup the liveness and readiness probes more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
  livenessProbe: {}
  readinessProbe:
    httpGet:
      path: /health
      port: http

  # This section is for setting up autoscaling more information can be found here: https://kubernetes.io/docs/concepts/workloads/autoscaling/
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80
    stabilizationWindowSeconds: 300

  networkPolicy:
    enabled: false
    ingress:
      enabled: false
      namespaceSelector: {}
      podSelector: {}

  # Additional volumes on the output Deployment definition.
  volumes: []

  # Additional volumeMounts on the output Deployment definition.
  volumeMounts: []

  nodeSelector: {}

  tolerations: []

  affinity: {}

showcaseCreator:
  # This will set the replicaset count more information can be found here: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/
  replicaCount: 1

  # This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
  image:
    repository: ghcr.io/4sure-tech/bc-wallet-showcase-creator
    # This sets the pull policy for images.
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""

  # This is for the secrets for pulling an image from a private repository more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
  imagePullSecrets: []

  logLevel: debug

  # Name of ConfigMap with extra environment variables; overrides global.extraEnvVarsCM if set
  extraEnvVarsCM: ""

  # Name of Secret with extra environment variables; overrides global.extraEnvVarsSecret if set
  extraEnvVarsSecret: ""

  # This is for setting Kubernetes Annotations to a Pod.
  podAnnotations: {}
  # This is for setting Kubernetes Labels to a Pod.
  podLabels: {}

  podSecurityContext: {}

  securityContext: {}

  # This is for setting up a service more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/
  service:
    type: ClusterIP
    port: 3050

  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

  # This is to setup the liveness and readiness probes more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
  livenessProbe: {}
  readinessProbe: {}

  # This section is for setting up autoscaling more information can be found here: https://kubernetes.io/docs/concepts/workloads/autoscaling/
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80
    stabilizationWindowSeconds: 300

  networkPolicy:
    enabled: false
    ingress:
      enabled: false
      namespaceSelector: {}
      podSelector: {}

  # Additional volumes on the output Deployment definition.
  volumes: []

  # Additional volumeMounts on the output Deployment definition.
  volumeMounts: []

  nodeSelector: {}

  tolerations: []

  affinity: {}

tractionAdapter:
  # This will set the replicaset count more information can be found here: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/
  replicaCount: 1

  # This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
  image:
    repository: ghcr.io/4sure-tech/bc-wallet-traction-adapter
    # This sets the pull policy for images.
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""

  # This is for the secrets for pulling an image from a private repository more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
  imagePullSecrets: []

  # Name of ConfigMap with extra environment variables; overrides global.extraEnvVarsCM if set
  extraEnvVarsCM: ""

  # Name of Secret with extra environment variables; overrides global.extraEnvVarsSecret if set
  extraEnvVarsSecret: ""

  # This is for setting Kubernetes Annotations to a Pod.
  podAnnotations: {}
  # This is for setting Kubernetes Labels to a Pod.
  podLabels: {}

  podSecurityContext: {}

  securityContext: {}

  # This is for setting up a service more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/
  service:
    type: ClusterIP
    port: 3000

  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

  # This is to setup the liveness and readiness probes more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
  livenessProbe: {}
  readinessProbe: {}

  # This section is for setting up autoscaling more information can be found here: https://kubernetes.io/docs/concepts/workloads/autoscaling/
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80
    stabilizationWindowSeconds: 300

  networkPolicy:
    enabled: false
    ingress:
      enabled: false
      namespaceSelector: {}
      podSelector: {}

  # Additional volumes on the output Deployment definition.
  volumes: []

  # Additional volumeMounts on the output Deployment definition.
  volumeMounts: []

  nodeSelector: {}

  tolerations: []

  affinity: {}

postgresql:
  enabled: true
  auth:
    enablePostgresUser: true
    username: postgres
    database: bcwallet
    # Let the chart generate and manage its own password
    password: ""
  primary:
    service:
      ports:
        postgresql: 5432
    persistence:
      enabled: true
      size: 8Gi
      storageClass: "local-path"
    resources:
      limits:
        cpu: 1000m
        memory: 1Gi
      requests:
        cpu: 250m
        memory: 256Mi
    podSecurityContext:
      enabled: false

rabbitmq:
  enabled: true
  auth:
    username: user
    # Let the chart generate and manage its own password
    password: ""
  extraPlugins: "rabbitmq_management,rabbitmq_peer_discovery_k8s"
  configuration: |-
    management.load_definitions = /app/load_definitions.json
  extraConfiguration: |-
    load_definitions = /app/load_definitions.json
  service:
    type: ClusterIP
    ports:
      amqp: 5672
      management: 15672
  persistence:
    enabled: true
    size: 8Gi
    storageClass: "local-path"
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 250m
      memory: 256Mi
  containerSecurityContext:
    enabled: false

debug: true  # Enable debug mode to create the debug-helper ConfigMap
